# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d6b12f9315abd1552f6508e12c1d74aeecbb0b4938c71ac89ae0a156a4a3e7a082f9277d643e5ee5046d3c69acfeccf4bab800d6e415efc3d48cfbf72278f753

test:
  secret_key_base: 967b89625bc0a430b9b82268b4eaac8c00040e2f6ec72fcbf7462a4b1bf57d9bed7327cc324548fa9415cd4d4c4587492244a41f07b574d6c75c671a5f53f250

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
